---
version: 0.2
env:
  code-artifact:
    domain: tts
    repos:
      tts-npm: [npm, jsii-npm]
      # tts-pypi: [pip, jsii-twine]
phases:
  install:
    runtime-versions:
      python: '3.8'
    commands:
      - npm install -g yarn projen jsii-release
  pre_build:
    commands:
      - yarn install
  build:
    commands:
      - projen build
  post_build:
    commands:
      - projen bump
      - jsii-release-npm
