---
version: 0.2
phases:
  install:
    runtime-versions:
      python: '3.8'
    commands:
      - echo npm install projen cdk jsii-release
  pre_build:
    commands:
      - echo
  build:
    commands:
      - projen build
  post_build:
    commands:
      - jsii
