---
version: 0.2
phases:
  install:
    runtime-versions:
      python: '3.8'
    commands:
      - npm install -g projen cdk jsii-release
  pre_build:
    commands:
      - projen
  build:
    commands:
      - projen build
  post_build:
    commands:
      - ls -al
      - export CODEARTIFACT_AUTH_TOKEN=`aws codeartifact get-authorization-token --domain tts --domain-owner 672648692041 --query authorizationToken --output text`
      - export TWINE_REPOSITORY_URL=`aws codeartifact get-repository-endpoint --domain tts --repository tts-pypi --format pypi --query repositoryEndpoint --output text`
      - export TWINE_USERNAME=aws
      - export TWINE_PASSWORD=$CODEARTIFACT_AUTH_TOKEN
      - jsii-release-pypi
